---
- hosts: all
  sudo: yes
  roles:
    - franklinkim.docker
    - franklinkim.docker-compose
  tasks:
    - name: Add vagrant user to docker-group
      user: name=vagrant
        groups=docker
        append=yes
    - name: Pull haproxy-config
      shell: docker pull factorial/haproxy-config
      # docker integration seems broken with current ansible version
      # docker_image:
      #   name: factorial/haproxy-config
