---
- hosts: all
  sudo: yes
  roles:
    - role: php-cli-ondrej
      php_cli_ondrej_version: 7.0
      php_cli_ondrej_mods_present: [{name: zip}, {name: json}, {name: xml}, {name: readline}, {name: mysql}, {name: memcache}, {name: memcached}, {name: msgpack}, {name: mstring}, {name: mcrypt}, {name: gd}, {name: curl}]
    - php-composer
    - kbrebanov.zip
  tasks:
    - name: remove possible old versions
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io
      become: true

    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - python-pip
      become: true

    - name: install python modules (for older versions of OS)
      pip:
        name: "{{item}}"
        state: present
      with_items:
      - urllib3
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1

    - name: Debian add docker key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: true
      when: "ansible_distribution == 'Debian'"

    - name: Ubuntu add docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true
      when: "ansible_distribution == 'Ubuntu'"

    - name: create repo line
      command: bash -c "echo \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" "
      register: docker_repo_line

    - debug:
        msg: "{{ docker_repo_line.stdout }}"

    - name: add docker repo
      apt_repository:
        repo: "{{ docker_repo_line.stdout }}"
        state: present
      become: true

    - name: install docker ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      become: true
    - name: "Install docker-compose"
      become: true
      shell: "curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
    - name: "Setup docker-compose"
      shell: "chmod +x /usr/local/bin/docker-compose"
      become: true
    - name: "Fix up docker-compose"
      become: true
      shell: "pip uninstall -y docker-py; pip uninstall -y docker; pip install docker"
    - name: Add vagrant user to docker-group
      user:
        name=vagrant
        groups=docker
        append=yes
    - name: Pull haproxy-config
      shell: docker pull factorial/haproxy-config
      # docker integration seems broken with current ansible version
      # docker_image:
      #   name: factorial/haproxy-config
    - name: Increase vm.max_map_count for elasticsearch
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
