module:
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  circle_ajax: 0
  circle_areas: 0
  circle_news: 0
  circle_newsletter: 0
  ckeditor: 0
  color: 0
  config: 0
  config_translation: 0
  content_translation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filename_transliteration: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  path: 0
  rdf: 0
  responsive_image: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  view_unpublished: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
theme:
  stable: 0
  classy: 0
  seven: 0
  circle: 0
  adminimal_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: minimal
