toolbar_items:
  - devel.cache_clear
  - devel.admin_settings_link
  - devel.elements_page
  - devel.entity_info_page
  - devel.reinstall
  - devel.route_info
  - devel.theme_registry
_core:
  default_config_hash: ysHEvvazIuaJ5BdY0dUw2_my_Q5hM8ypdXwFfaIrvMw
