<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function circle_news_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === 'views_exposed_form') {
    $view = $form_state->getStorage('view');
    if ($view['view']->id() === 'news') {
      $query = \Drupal::database()->select('node__field_category', 'category');
      $categories = $query->fields('category', ['field_category_target_id'])
                          ->distinct()
                          ->condition('langcode', \Drupal::languageManager()->getCurrentLanguage()->getId())
                          ->execute()
                          ->fetchCol();

      foreach ($form['category']['#options'] as $key => $label) {
        if (is_numeric($key) && !in_array($key, $categories)) {
          unset($form['category']['#options'][$key]);
        }
      }

      if (count($form['category']['#options']) === 1) {
        unset($form['category']);
      }
    }
  }
}