<?php
use Drupal\views\Views;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function circle_news_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === 'views_exposed_form') {
    $view = $form_state->getStorage('view');
    if ($view['view']->id() === 'news') {
      $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();
      foreach ($form['category']['#options'] as $key => $label) {
        if (is_numeric($key) && !in_array($key, $categories)) {
          $query = \Drupal::entityQuery('node')
                    ->condition('status', 1)
                    ->condition('type', 'article')
                    ->condition('field_category.entity.tid', $key, '=', $lang_code);
          $nids = $query->execute();
          if (empty($nids)) {
            unset($form['category']['#options'][$key]);
          }
        }
      }

      if (count($form['category']['#options']) === 1) {
        unset($form['category']);
      }
    }
  }
}
