name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2017-01-04
version: '8.2.5'
core: '8.x'
project: 'drupal'
datestamp: 1483529982
