host: multibasebox.test
requires: 2.0.1
port: 22
user: vagrant
password: vagrant
rootFolder: /vagrant
environment:
  ROOT_FOLDER: "%dockerHost.rootFolder%/%host.docker.projectFolder%"
blueprint:
  inheritsFrom: mbb
  configName: '%project-slug%-%slug.with-hyphens.without-feature%.test'
  branch: '%identifier%'
  host: '%project-slug%-%slug.with-hyphens.without-feature%.test'
  database:
    name: '%slug.without-feature%_mysql'
  docker:
    projectFolder: '%project-slug%--%slug.with-hyphens.without-feature%'
    vhost: '%project-slug%-%slug.with-hyphens.without-feature%.test'
    name: '%project-slug%%slug.without-feature%_web_1'

tasks:
  spinUp:
    - execute(docker,run)
  spinDown:
    - execute(docker,stop)
  deleteContainer:
    - execute(docker,rm)
  start:
    - docker start %host.docker.name%
    - run_task(reload_haproxy)

  stop:
    - if docker ps | grep -qw %host.docker.name% ; then docker stop %host.docker.name%; fi
    - execute(docker, reload_haproxy)

  rm:
    - if docker ps -a | grep -qw %host.docker.name% ; then docker rm %host.docker.name%; fi

  rmi:
    - if docker images | grep -qw %host.docker.name%/%host.docker.tag% ; then docker rmi %host.docker.name%/%host.docker.tag%; fi

  logs:
    - docker logs %host.docker.name%

  ps:
    - docker ps

  images:
    - docker images

  reload_haproxy:
    - touch /tmp/haproxy
  check_project_folder:
    - fail_on_missing_directory(%dockerHost.rootFolder%/%host.docker.projectFolder%, Could not find projectFolder '%host.docker.projectFolder%' -- please check your configuration 'docker.projectFolder' in '%host.config_name%'!)
  rebuild:
    - execute(docker, check_project_folder)
    - cd %dockerHost.rootFolder%/%host.docker.projectFolder%/_tools/docker && ./run.sh %host.docker.name% %dockerHost.rootFolder%/%host.docker.projectFolder% --webRoot %host.rootFolder% --rebuild --ssh %host.port%  --no-install --vhost %host.host%
    - execute(docker, reload_haproxy)
    - execute(docker, waitForServices)
    - execute(docker, copySSHKeyToDocker)

  run:
    - execute(docker, check_project_folder)
    - cd %dockerHost.rootFolder%/%host.docker.projectFolder%/_tools/docker && ./run.sh %host.docker.name% %dockerHost.rootFolder%/%host.docker.projectFolder% --webRoot %host.rootFolder%  --ssh %host.port%  --no-install --vhost %host.host%
    - execute(docker, reload_haproxy)
    - execute(docker, waitForServices)


