tips:
  language-edit-langcode:
    label: Sprachkürzel
  language-edit-label:
    label: Sprachname
  language-edit-direction:
    label: Sprachlaufrichtung
  language-edit-continue:
    label: 'Fortsetzen auf'
