label: Benutzer
description: 'Menschen finden und verwalten, die mit Ihrer Website in Kontakt stehen.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            next: 'Weiter >'
            first: '« Anfang'
            last: 'Ende »'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        user_bulk_form:
          label: Massenaktualisierung
        name:
          label: Benutzername
        status:
          label: Status
        roles_target_id:
          label: Rollen
        created:
          label: 'Mitglied seit'
        access:
          label: 'Letzter Zugriff'
        operations:
          label: Operationen
        mail:
          separator: ', '
      filters:
        combine:
          expose:
            label: 'Name oder E-Mail-Adresse enthält'
        roles_target_id:
          expose:
            label: Rolle
        permission:
          expose:
            label: Berechtigung
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Aktiv
                value: '1'
              2:
                title: Gesperrt
      title: Benutzer
      empty:
        area_text_custom:
          content: 'Keine Personen verfügbar.'
      use_more_text: mehr
  page_1:
    display_title: Seite
    display_options:
      menu:
        title: Liste
        description: 'Menschen finden und verwalten, die mit Ihrer Website in Kontakt stehen.'
      tab_options:
        title: Benutzer
        description: 'Verwalten von Benutzerkonten, Rollen und Zugriffsrechten.'
